# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Online CV of Senthil Prabhu'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: navbar

# Site footer
footer:
  block: minimal
  copyright:
    notice: '© {year} senthilprabhu.com. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  
  # For multilingual sites, show a language chooser in the footer?
  show_translations: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Link to edit page on GitHub
  repository:
    url: 'https://github.com/senthil-mookiah/senthil-mookiah.github.io'
    content_dir: content
    branch: main

# Get Feedback
  feedback:
    responses:
      positive: 'Glad to hear it! [Any ideas for improvements?](https://github.com/senthil-mookiah/senthil-mookiah.github.io/issues/new)'
      negative: 'Sorry to hear that. [Please tell us how we can improve](https://github.com/senthil-mookiah/senthil-mookiah.github.io/issues/new).'
